import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";

const playfont = Play({
    weight: ["400", "700"],
    variable: "--font-play",
});

export const metadata: Metadata = {
    title: "Yago Claros Seijo",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es-ES">
            <body
                className={`${playfont.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
